(() => {
 const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const names={TMP:'Tempo',LOC:'Local',MNR:'Modo',CAU:'Causa',PNC:'Finalidade',PRP:'Finalidade',EXT:'Extensão ou intensidade',ADV:'Modificação geral',SRC:'Origem',DIR:'Direção',NEG:'Negação',DIS:'Discurso',MOD:'Modalidade',REC:'Reciprocidade'};
 const label=v=>{const raw=String(v||'');const m=raw.match(/^ARGM-([A-Z]+)/i);return m?(names[m[1].toUpperCase()]||'Modificador')+' ('+raw+')':raw;};
 const value=v=>v==null||v===''||v==='_'?'Sem marcação':typeof v==='object'?label(v.label)+': “'+(v.realization||'')+'”':/^([^:]+):(\d+)$/.test(String(v))?label(String(v).split(':')[0])+', ligado ao predicador na posição '+String(v).split(':')[1]:label(v);
 const add=(host,title,text)=>{const p=el('p');p.append(el('strong',title+': '),document.createTextNode(text||'Não documentado na fonte recuperada.'));host.append(p);return p;};
 const marks=(host,title,rows)=>{host.append(el('h4',title));if(!rows?.length){host.append(el('p','Nenhuma marca registrada nesta categoria.'));return;}const ul=el('ul');for(const m of rows){const li=el('li',value(m));ul.append(li)}host.append(ul);};
 const card=(title,text)=>{const a=el('article');a.className='human-provenance-card';a.append(el('h3',title));if(text)a.append(el('blockquote',text));return a;};
 const technical=(host,fields)=>{const d=el('details');d.append(el('summary','Localizar a fonte e conferir os identificadores'));const dl=el('dl');for(const [k,v] of Object.entries(fields)){if(v==null)continue;dl.append(el('dt',k),el('dd',String(v)));}d.append(dl);host.append(d);};
 const fold=v=>String(v??'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('pt');
 const render=(inputId,outId,data,build)=>{const input=document.getElementById(inputId),out=document.getElementById(outId);if(!input||!out)return;let page=0;const show=()=>{const q=fold(input.value),found=data.filter(x=>fold(JSON.stringify(x)).includes(q));out.replaceChildren(el('p',found.length+' registros encontrados.'));for(const x of found.slice(page*20,(page+1)*20))out.append(build(x));const controls=el('div');for(const [text,delta] of [['Anterior',-1],['Próxima',1]]){const b=el('button',text);b.type='button';b.disabled=delta<0?page===0:(page+1)*20>=found.length;b.addEventListener('click',()=>{page+=delta;show();out.scrollIntoView({block:'start'});});controls.append(b);}out.append(controls);};input.addEventListener('input',()=>{page=0;show()});show();};
 const style=el('style');style.textContent='.human-provenance-card{padding:18px;margin:18px 0;border:1px solid #69758b;border-radius:8px;background:#383e48;line-height:1.65}.human-provenance-card blockquote{margin:10px 0;padding:10px 14px;border-left:3px solid #a8b8dc;background:#303641;overflow-wrap:anywhere}.human-provenance-card h4{margin-bottom:6px}.human-provenance-card dl{display:grid;grid-template-columns:minmax(100px,1fr) minmax(0,3fr);gap:8px}.human-provenance-card dt{font-weight:bold}.human-provenance-card dd{margin:0;overflow-wrap:anywhere}#history-results button,#argm-history-results button,#historical-argm-results button,#provenance-results button{margin:8px;padding:10px 16px;background:#455987;color:white;border:1px solid #a7b9ff;border-radius:6px}button:disabled{opacity:.5}';document.head.append(style);
 window.NBDSProvenance={el,label,value,add,marks,card,technical,render};
 const history=fetch('historical-provenance.json').then(r=>r.json());window.NBDSHistory=history;
})();
